image : registry.gitlab.com/liquiduniverse/docgen:latest

stages:
    #- build
   # - build-core
    #- test
   # - test-core
    - pages
    - update-parent

#build:
    #stage: build
    #script:
       # - dotnet build
   # artifacts:
        #paths:
          #  - ./build/
 
#build-core:
    #stage: build-core
   # script:
       # - dotnet build
    #artifacts:
       # paths:
           # - ./build/

#test:
    #stage: test
   # script:
        #- dotnet test AtomicAssetsApiClient.Test/AtomicAssetsApiClient.Test.csproj

#test-core:
    #stage: test-core
    #script:
        #- dotnet test AtomicAssetsApiClient.Core.Test/AtomicAssetsApiClient.Core.Test.csproj

pages:
    stage: pages
    script:
        - doxygen documentation/doxygen/Doxyfile
        - doxybook2 --input  documentation/doxyoutput/xml --output  documentation/gitbook --config documentation/doxybook-config/gitbook/.doxybook/config.json --summary-input documentation/doxybook-config/gitbook/SUMMARY.md.tmpl --summary-output documentation/gitbook/SUMMARY.md 
        - gitbook build documentation/gitbook documentation/gitbook_output
        - cp -r documentation/gitbook_output public
    
  
    artifacts:
      paths:
       - public
       - documentation

update-parent:
   stage: update-parent
   script:
    - git clone https://ashleewawa17@gmail.com:Gamedesignerlee1@gitlab.com/ashleewawa17/wax-1.git
    - git config --global user.emai "ashleewawa17@gmail.com"
    #- git add . 
    #- git commit -m"Update"
   # - git push "https://gitlab-ci-token:$Atomic@$gitlab.com/$liquiduniverse/unityeosclientplugins/theliquiidbible_gitbook
   
