name: Deploy UPM

on: [push]

jobs:
  split-upm:
    name: Split UPM branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: split upm branch
      run: |
        git branch -d upm &> /dev/null || echo upm branch not found # recreate the upm branch each time
        echo "********************** ROOT **********************"
        ls
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git checkout -b upm unity_develop                            # create the upm branch and checkout the branch
        git ls-files | grep '\.csproj$' | xargs git rm               # remove all .csproj files
        git ls-files | grep '\.csproj.meta$' | xargs git rm          # remove all .csproj.meta files
        git ls-files | grep '\.sln$' | xargs git rm                   # remove all .sln files
        git ls-files | grep '\.sln.meta$' | xargs git rm              # remove all .sln.meta files
        git rm -r .github
        git commit -am "initial commit"
        echo "********************** ROOT **********************"
        ls
        git push -u origin upm --force                              # commit the branch
      
      