name: Deploy UPM

on: [push]

jobs:
  split-upm:
    name: Split UPM branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: unity_develop
        fetch-depth: 0
    - name: split upm branch
      run: |
        git branch -d upm &> /dev/null || echo upm branch not found # recreate the upm branch each time
        echo "********************** ROOT **********************"
        ls
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git checkout -b upm                                           # create the upm branch and checkout the branch
        git rm -r .github
        git commit -am "initial commit"
        echo "********************** ROOT **********************"
        ls
        git push -u origin upm --force                              # commit the branch
      
      